[project]
name = "react-agent"
version = "0.1.0"
description = "A ReAct (Reason and Act) AI agent that handles tool call"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "curl-cffi>=0.11.4",
    "ollama>=0.11.7",
    "python-dotenv>=1.0.1",
]
